on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Code Quality
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Create config file
        run: echo '{"firebase":{"api-key":"${{ secrets.FIREBASE_API_KEY }}"}}' > config.json
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Archive test Artifact
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
  sonarcloud:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download test Artifact
        uses: actions/download-artifact@master
        with:
          name: coverage
          path: coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
